version: '2.1'

services:
  zidane:
    container_name: zidane
    build: .
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - gopamoja

networks:
  gopamoja:
    external: true
